name: Publish
run-name: Publish to NPM
on:
  release:
    types: ['published']
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: ${{ github.ref_name }}
      deployUrl: https://api.vercel.com/v6/deployments?app=lettr&limit=1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Create .env for dist
        run: |
          echo "APP_VERSION=${{ env.version }}" >> dist/.env
          echo "API_URL=$(curl -sL '${{ env.deployUrl }}' -H 'Authorization: Bearer ${{ secrets.VERCEL_API_TOKEN }}' | jq -r '.deployments[0].url')/api" >> dist/.env
          echo "BASE_URL=${{ vars.BASE_URL }}" >> dist/.env
          echo "SUPABASE_URL=${{ vars.SUPABASE_URL }}" >> dist/.env
          echo "SUPABASE_ANON_KEY=${{ vars.SUPABASE_ANON_KEY }}" >> dist/.env
          echo "NPM_PACKAGE_URL=${{ vars.NPM_PACKAGE_URL }}" >> dist/.env
      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
