name: Publish
run-name: Publish to NPM
on:
  release:
    types: ['published']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}